version: 2.1

parameters:
  replay-days:
    type: integer
    default: 2
  commit-delay:
    type: integer
    default: 10

jobs:
  run_replay_job:
    docker:
      - image: cimg/python:3.12
    resource_class: small
    environment:
      GITHUB_REPO_SLUG: AwesomeCICD/react
    steps:
      - checkout
      - run:
          name: Install Python Requirements
          command: pip install -r requirements.txt
      - run:
          name: Run Replay Script
          no_output_timeout: 20m
          # Add --branch branch_name to customize the branch used
          command: |
                  python3 replay_commits.py \
                    --upstream-repo-url $UPSTREAM_REPO \
                    --config-path $CONFIG_PATH \
                    --github-repo-slug $GITHUB_REPO_SLUG \
                    --github-token $GITHUB_TOKEN \
                    --log-path . \
                    --commit-delay << pipeline.parameters.commit-delay >>  \
                    --replay-days << pipeline.parameters.replay-days >>

workflows:
  daily_replay_workflow:
    jobs:
      - run_replay_job:
          context:
            - replay-commits
          filters:
            branches:
              only: main